global:
  scrape_interval:     15s
  evaluation_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'Prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: 'Main'
    scrape_interval: 5s
    static_configs:
      - targets:
        - nodeexporter:9100

  - job_name: 'Exporter-1'
    scrape_interval: 5s
    static_configs:
      - targets:
        - Exporter1_IP:9100

  - job_name: 'Exporter-2'
    scrape_interval: 5s
    static_configs:
      - targets:
        - Exporter2_IP:9100

  - job_name: 'Containers'
    scrape_interval: 10s
    static_configs:
      - targets:
        - cadvisor:8080

  - job_name: 'Jenkins'
    scrape_interval: 5s
    metrics_path: /prometheus/
    static_configs:
      - targets: ['MyJenkinsServer']